// ── Core module barrel ──────────────────────────────────────────────
export { Cmd, TreeView, Context, Panel } from "./commands";
export { Regex } from "./regex";
export { toHeadingSlug, toKebabCaseLower, toPathSlug } from "./slug";
export { createCodeLensProvider, createStatefulCodeLensProvider, codeLens } from "./codeLens";
export type { CodeLensGenerator, StatefulCodeLensOptions } from "./codeLens";
export { CODELENS_GENERATORS } from "./codelensGenerators";
export { INLINE_FORMATS } from "./inlineFormats";
export { SIMPLE_COMMANDS, slashHandler } from "./simpleCommands";
export type { SlashCommandHandler } from "./simpleCommands";
export { updateCwd } from "./cwd";
export { createSlashCompletionProvider, SLASH_COMMANDS, SlashCommand } from "./slashCommands";
export { createStructureLinter } from "./structureLint";
export { initBlockIndex, getBlockIndex } from "./blockIndex";
export type { BlockIndex, CodeFence, DetailsBlock, MarkdownCallout, MarkdownTable } from "./blockIndex";
export { initWebviewShell } from "./webviewShell";
export { createFileHashTracker } from "./fileHashTracker";
export { computeCursorContext } from "./cursorContext";
export type { CursorContext } from "./cursorContext";
export { Filter, CmdFilter } from "./cmdFilter";
export { parseCommandArgs } from "./commandArgs";
export type { ParsedCommandArgs } from "./commandArgs";
export { guid, shortId } from "./ids";
export { Markers } from "./markers";
export type { MarkerKey } from "./markers";
export { WorkspaceCache } from "./workspaceCache";
export type { WorkspaceCacheOptions } from "./workspaceCache";
